name: Branch Release
author: David Dearden
description: >-
  Automate the release of code where the dist files need to published to a GitHub branch. Use Conventional Commits to
  automatically update the release version and create GitHub release notes, then build and push to the release branch
  with git tags.
branding:
  icon: git-branch
  color: red

runs:
  using: node20
  main: dist/index.js

inputs:
  github-token:
    description: A github token with access to write to the repository.
    required: true
  build-command:
    description: The command to build the dist files for the project (ex. npm run build)
  changelog-titles:
    description: >-
      A JSON encoded object, mapping the conventional commit type to the section title to use in the changelog for that
      type. These values will be merged into and override the default titles. (ex. `{ "feat": "New Features" }`)
  disable-git-tagging:
    description: Disable setting and/or updating the git tags.
    default: "false"
  disable-github-release:
    description: Create a GitHub Release.
    default: "false"
  dry-run:
    description: Run the action without actually releasing the package or pushing git tags.
    default: "false"
  get-release-title-from-pr:
    description: >-
      Attempt to get the PR title from a PR associated to the git sha. If it is found, use the PR title as the release
      title. If not found, fall back to the release tag name. If the `release-title` has a truthy value, it will
      override this option. Note: The GITHUB_TOKEN requires `pull-requests: read` permissions.
    default: "false"
  git-tag-suffix:
    description: A value append to the git tags.
  latest-tag-name:
    description: The tag used to track the latest commit on the release branch.
    default: latest
  major-types:
    description: A comma-separated list of conventional commit types that trigger a major version change.
  minor-types:
    description: >-
      A comma-separated list of conventional commit types that trigger a minor version change. It defaults to `feat`
  prepend-version-to-release-title:
    description: >-
      Whether to prepend the release version to the release title. Note: this only applies when
      `get-release-title-from-pr` is `true`.
    default: "false"
  release-branch:
    description: The name of the branch to publish the release to.
    default: release
  release-title:
    description:
      The title to use for the GitHub release. If not set, or an empty string, the release tag name will be used.
  tracking-tag:
    description: The name of the tag to put on the source branch to track the source of the latest Release.
    default: latest-src
  version-override:
    description: >-
      The version to use for publishing the package instead of determining the version using conventional commits.

outputs:
  current-version:
    description: The version of the package before it is updated.
  increment-type:
    description: The type of version increment (if applicable) in ['major', 'minor', 'patch'].
  next-version:
    description: The new version of the package (ex. '1.2.3').
  next-version-major:
    description: The major portion of the new version of the package (ex. '1').
  next-version-minor:
    description: The minor portion of the new version of the package (ex. '2').
  next-version-patch:
    description: The patch portion of the new version of the package (ex. '3').
