name: Pull Request Checks

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  lint-format-test:
    name: Lint, Format, Test
    runs-on: ubuntu-latest

    env:
      ENV: ci
      HUSKY: '0'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: npm ci

      - name: Check Formatting
        run: npm run format:ci

      - name: Typescript Type Checks
        run: npm run type

      - name: Run Linter
        run: npm run lint:ci

      - name: Run Unit Tests
        id: unit_tests
        run: npm run test:ci

      - name: Generate Unit Test Report
        if: |
          ( success() || failure() )
          && ( steps.unit_tests.conclusion == 'success' || steps.unit_tests.conclusion == 'failure' )
        uses: dorny/test-reporter@v1.8.0
        with:
          name: Vitest Report
          path: reports/vitest-junit-report.xml
          reporter: jest-junit
          fail-on-error: false

      - name: Report Coverage
        if: |
          ( success() || failure() )
          && ( steps.unit_tests.conclusion == 'success' || steps.unit_tests.conclusion == 'failure' )
        uses: davelosert/vitest-coverage-report-action@v2
